import { useState } from "react";
import ReactMarkdown from "react-markdown";
import { ChevronDown } from "lucide-react";
import type { QueryResponse } from "@/types/api";
import CitationCard from "./CitationCard";

interface AnswerCardProps {
  data: QueryResponse;
}

const AnswerCard = ({ data }: AnswerCardProps) => {
  const [citationsOpen, setCitationsOpen] = useState(true);

  const hasIcmr = data.citations.some((c) => c.source_type === "icmr");
  const hasPubmed = data.citations.some((c) => c.source_type === "pubmed");

  // Replace [N] with clickable links
  const processedAnswer = data.answer;

  return (
    <div className="w-full max-w-[760px] mx-auto px-4 sm:px-8 animate-fade-up">
      <div className="bg-card rounded-xl border border-border overflow-hidden">
        {/* Header */}
        <div className="flex items-center justify-between px-5 py-3 border-b border-border">
          <div className="flex items-center gap-2">
            <span className="text-lg">🩺</span>
            <span className="font-semibold text-foreground">Clinical Answer</span>
          </div>
          <div className="flex items-center gap-1.5">
            {hasIcmr && (
              <span className="text-[11px] font-medium px-2 py-0.5 rounded-full bg-primary text-primary-foreground">
                ICMR
              </span>
            )}
            {hasPubmed && (
              <span className="text-[11px] font-medium px-2 py-0.5 rounded-full bg-pubmed text-pubmed-foreground">
                PubMed
              </span>
            )}
          </div>
        </div>

        {/* Answer body */}
        <div className="p-5">
          <div className="bg-primary-light/50 rounded-lg p-4 prose prose-sm prose-slate max-w-none text-[15px] leading-[1.7]">
            <ReactMarkdown
              components={{
                a: ({ children, ...props }) => (
                  <a {...props} className="text-primary hover:underline" target="_blank" rel="noopener noreferrer">
                    {children}
                  </a>
                ),
              }}
            >
              {processedAnswer.replace(
                /\[(\d+)\]/g,
                (_, num) => `[${num}](#citation-${num})`
              )}
            </ReactMarkdown>
          </div>

          <p className="text-xs text-muted-foreground mt-3">
            Generated by {data.model} · {data.chunks_retrieved} sources retrieved
          </p>
        </div>

        {/* Citations */}
        {data.citations.length > 0 && (
          <div className="border-t border-border">
            <button
              onClick={() => setCitationsOpen(!citationsOpen)}
              className="w-full flex items-center justify-between px-5 py-3 text-sm font-semibold text-foreground hover:bg-muted/30 transition-colors"
            >
              <span>📚 Sources Used ({data.citations.length})</span>
              <ChevronDown className={`w-4 h-4 transition-transform ${citationsOpen ? "rotate-180" : ""}`} />
            </button>
            {citationsOpen && (
              <div className="px-5 pb-5 space-y-3">
                {data.citations.map((citation) => (
                  <CitationCard key={citation.index} citation={citation} />
                ))}
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
};

export default AnswerCard;
